export const MAIN_DATA = [
  {
    id: 1,
    name: "Chopta Tungnath",
    images:[],
    prices: [
      { type: "Quad Sharing", price: 4999 },
      { type: "Triple Sharing", price: 5499 },
      { type: "Double Sharing", price: 5999 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Chopta Valley",
      "Devprayag",
      "ChandraShila",
      "Haridwar",
      "Rishikesh",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in chopta valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
  },
  {
    id: 2,
    name: "Manali - Rohtang - Kasol",
    images:[],
    prices: [
      { type: "Quad Sharing", price: 4999 },
      { type: "Triple Sharing", price: 5499 },
      { type: "Double Sharing", price: 5999 },
    ],
    duration: {
      day: 6,
      night: 5,
    },
    places_covered: [
      "Atal Tunnel",
      "Sissu",
      "Hidimba/Vaishisth Temple",
      "Mall Road",
      "Manikaran",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in Tirthan valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
  },
  {
    id: 3,
    name: "Udaipur - Mount Abu",
    images:[],
    prices: [
      { type: "Quad Sharing", price: 4999 },
      { type: "Triple Sharing", price: 5499 },
      { type: "Double Sharing", price: 5999 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "City Palace",
      "Lake Picola",
      "City Tour",
      "Mount Abu",
      "Local Sightseeing",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in Rajasthan",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
  },
  {
    id: 4,
    name: "Tirthan - Jibhi - Jalori",
    images:[],
    prices: [
      { type: "Quad Sharing", price: 4999 },
      { type: "Triple Sharing", price: 5499 },
      { type: "Double Sharing", price: 5999 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Tirthan Valley",
      "Jibhi Waterfall",
      "Sarolsar Lake",
      "Mini Thainland",
      "Jalori Pass",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in tirthan valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
  },
  {
    id: 5,
    name: "Mcleodganj - Triund",
    images:[],
    prices: [
      { type: "Quad Sharing", price: 5499 },
      { type: "Triple Sharing", price: 5999 },
      { type: "Double Sharing", price: 6499 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Triund Valley",
      "Dharamshalla",
      "Dalai Lama Temple",
      "Dal Lake",
      "Cricket Stadium",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in parvati valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
  },
  {
    id: 6,
    name: "Kasol - Kheerganga",
    images:[],
    prices: [
      { type: "Quad Sharing", price: 4999 },
      { type: "Triple Sharing", price: 5499 },
      { type: "Double Sharing", price: 5999 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Parvati Valley",
      "Manikaran",
      "Kasol Market",
      "Mini Thailand",
      "Hot Spring",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in parvati valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
  },
];
