import { MainDataType } from "@fod/constants/types";

export const HOMEPAGE_VIDEO_URL =
  "https://res.cloudinary.com/dgghqzaxo/video/upload/v1761249884/FOD%20Holidays/fod_hrms5i.mp4";

const DEFAULT_WTSP_URL =
  "https://api.whatsapp.com/send/?phone=919779434405&text&type=phone_number&app_absent=0";

export const MAIN_DATA: MainDataType[] = [
  {
    id: 1,
    name: "Chopta Tungnath",
    desc: "Embark on a scenic adventure to Chopta Valley and Tungnath Temple. Enjoy breathtaking mountain views, cozy stays, bonfires, and starry nights while exploring Rishikesh and Haridwar with expert guides and great company.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131160/FOD%20Holidays/Chopta%20Tungnath/ashwini-chaudhary-monty-bsVt1_On_gk-unsplash_nwajyv.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131172/FOD%20Holidays/Chopta%20Tungnath/ankit-mishra-Q-GnjgTsqz0-unsplash_aviisj.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131172/FOD%20Holidays/Chopta%20Tungnath/gaurav-k-CV7KPRM6fHc-unsplash_zgkzcu.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131162/FOD%20Holidays/Chopta%20Tungnath/joshi-milestoner-3eT3tuFGKqs-unsplash_bt5frw.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131162/FOD%20Holidays/Chopta%20Tungnath/prashant-bamnawat-JW_Tbqa82CY-unsplash_cczxg6.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131159/FOD%20Holidays/Chopta%20Tungnath/aditya-siva-HlQi14Q_iO0-unsplash_ssk29x.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 5999 },
      { type: "triple", label: "Triple Sharing", price: 6499 },
      { type: "double", label: "Double Sharing", price: 6999 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Chopta Valley",
      "Devprayag",
      "ChandraShila",
      "Haridwar",
      "Rishikesh",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in chopta valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 2,
    name: "Manali - Rohtang - Kasol",
    desc: "Discover the charm of Manali and the tranquility of Kasol on this stunning Himalayan getaway. Visit Rohtang Pass, Atal Tunnel, and Manikaran, with comfortable stays, bonfires, and DJ nights included.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131840/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/vishy-9ttisCSNCOc-unsplash_mwpc5f.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131841/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/sunil-kumar-npNDDOy7kNM-unsplash_f46wzx.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131840/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/vishal-bhutani-ugyfweYokVA-unsplash_tqivia.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131839/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/surya-teja-oIXJ839p55k-unsplash_jccqcn.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131837/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/pranav-s-ZlSdlSld8LQ-unsplash_q4ns8q.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131834/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/naman-jaswani-Xpwj1j1HX34-unsplash_hfsfpq.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131833/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/gagan-deep-8oB7HUfvK1o-unsplash_xeiqnc.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131832/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/perminder-klair-R-lq14hx85I-unsplash_yosmhv.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131831/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/arul-pratheep-s-5bNfi2C_BOA-unsplash_abesbw.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131830/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/iftekhar-nibir-PKHwl4CK7j8-unsplash_f0bock.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131828/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/aditya-chache-IeWEtwu2t6g-unsplash_yuv3fp.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131820/FOD%20Holidays/Manali%20-%20Rohtang%20-%20Kasol/aditya-chache-F4ybv3lThTs-unsplash_xhdgfr.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 5999 },
      { type: "triple", label: "Triple Sharing", price: 6499 },
      { type: "double", label: "Double Sharing", price: 6999 },
    ],
    duration: {
      day: 6,
      night: 5,
    },
    places_covered: [
      "Atal Tunnel",
      "Sissu",
      "Hidimba/Vaishisth Temple",
      "Mall Road",
      "Manikaran",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in Tirthan valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 3,
    name: "Udaipur - Mount Abu",
    desc: "Experience the royal beauty of Udaipur and the cool hills of Mount Abu. Explore palaces, lakes, and historic sights while enjoying bonfires, scenic stays, and authentic Rajasthani hospitality throughout your journey.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761133106/FOD%20Holidays/Udaipur%20-%20Mount%20Abu/pranav-panchal-IEArgDckRuQ-unsplash_hpefr6.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761133117/FOD%20Holidays/Udaipur%20-%20Mount%20Abu/kashish-lamba-JfowJjlcK8A-unsplash_hrroxc.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761133112/FOD%20Holidays/Udaipur%20-%20Mount%20Abu/vivek-1pNm4DFts4U-unsplash_xv3vk1.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761133111/FOD%20Holidays/Udaipur%20-%20Mount%20Abu/vinay-bhadeshiya-GvOUiUC-O2Q-unsplash_mit2ax.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761133108/FOD%20Holidays/Udaipur%20-%20Mount%20Abu/romi-kalathiya-Bxwa1-VoJ-A-unsplash_ivpeyt.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761133102/FOD%20Holidays/Udaipur%20-%20Mount%20Abu/jainam-mehta-AVFjDGbqiqE-unsplash_nqffyd.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132569/FOD%20Holidays/Udaipur%20-%20Mount%20Abu/rimjhim-agrawal-P6I33ztlBzs-unsplash_dkcp6s.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 5999 },
      { type: "triple", label: "Triple Sharing", price: 6499 },
      { type: "double", label: "Double Sharing", price: 6999 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "City Palace",
      "Lake Picola",
      "City Tour",
      "Mount Abu",
      "Local Sightseeing",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in Rajasthan",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 4,
    name: "Tirthan - Jibhi - Jalori",
    desc: "Unwind in the hidden gems of Himachal—Tirthan, Jibhi, and Jalori. Enjoy serene waterfalls, mountain lakes, cozy stays, bonfires, and scenic treks in the lap of nature with fellow explorers.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132485/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/payal-badhran-sWuY2RSVLBk-unsplash_boshmy.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132494/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/uday-pratap-singh-atwal-Sd23uGga0dU-unsplash_fqmrse.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132493/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/uday-pratap-singh-atwal-f36tdJtLijM-unsplash_ydrzod.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132490/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/anirudh-thakur-lKm-4J9zwds-unsplash_z5a0sw.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132487/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/uday-pratap-singh-atwal-cyoF1edNhbI-unsplash_xuikec.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132486/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/nandita-dhindsa-LmzRh0mXvoc-unsplash_qhefxo.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132485/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/hrishikesh-sarode-ufTHHDWJLj8-unsplash_zhodeq.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132483/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/anmol-arora-DqnvbeG1790-unsplash_m0vc9s.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132483/FOD%20Holidays/Tirthan%20-%20Jibhi%20-%20Jalori/jalori-pass-17_bwwvhr.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 5999 },
      { type: "triple", label: "Triple Sharing", price: 6499 },
      { type: "double", label: "Double Sharing", price: 6999 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Tirthan Valley",
      "Jibhi Waterfall",
      "Sarolsar Lake",
      "Mini Thainland",
      "Jalori Pass",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in tirthan valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 5,
    name: "Mcleodganj - Triund",
    desc: "Escape to Mcleodganj’s calm and trek to the scenic Triund Valley. Visit Dalai Lama Temple, Dal Lake, and Dharamshala, with evenings spent around bonfires under the stars.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131942/FOD%20Holidays/Mcleodganj%20-%20Triund/shashank-verma-4q3oidhiDXY-unsplash_r5a69g.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131948/FOD%20Holidays/Mcleodganj%20-%20Triund/nikhil-v-BzO5EBSCXv4-unsplash_zfzjmf.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131946/FOD%20Holidays/Mcleodganj%20-%20Triund/clasiqh-U9IdYM7rc8I-unsplash_yrhtif.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131944/FOD%20Holidays/Mcleodganj%20-%20Triund/ankit-kumar-tXaCXpPIgMU-unsplash_cqhanr.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131941/FOD%20Holidays/Mcleodganj%20-%20Triund/tejashvi-verma-cyWRGbQx3pE-unsplash_m9akl4.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131939/FOD%20Holidays/Mcleodganj%20-%20Triund/lakshya-thakur-sPZu5DFbM44-unsplash_hfp5wq.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131937/FOD%20Holidays/Mcleodganj%20-%20Triund/aditya-chache-nGp7qL9N8bY-unsplash_wrsjwl.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131941/FOD%20Holidays/Mcleodganj%20-%20Triund/tejashvi-verma-najmIKbujfE-unsplash_xkbtie.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 6499 },
      { type: "triple", label: "Triple Sharing", price: 6999 },
      { type: "double", label: "Double Sharing", price: 7499 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Triund Valley",
      "Dharamshalla",
      "Dalai Lama Temple",
      "Dal Lake",
      "Cricket Stadium",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in parvati valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 6,
    name: "Kasol - Kheerganga",
    desc: "Explore the magic of Parvati Valley with a trek to Kheerganga. Relax in natural hot springs, wander Kasol’s markets, and soak in mountain views with guided travel and lively bonfire nights.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131641/FOD%20Holidays/Kasol%20-%20Kheerganga/rishabh-dharmani-bsXoqhN299A-unsplash_uamxna.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131651/FOD%20Holidays/Kasol%20-%20Kheerganga/lucas-hemingway-dpHgkc533z4-unsplash_rwxnpe.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131650/FOD%20Holidays/Kasol%20-%20Kheerganga/shlok-jethwa-dgyl6znQ3Q4-unsplash_ggvf5f.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131649/FOD%20Holidays/Kasol%20-%20Kheerganga/prashanth-yadav-s4L9AcSEvGE-unsplash_obkq8b.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131648/FOD%20Holidays/Kasol%20-%20Kheerganga/md-sani-lfz82SS1BAk-unsplash_h1rfbr.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131638/FOD%20Holidays/Kasol%20-%20Kheerganga/nayan-tara-sOreumdCaKI-unsplash_ksj9uv.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131637/FOD%20Holidays/Kasol%20-%20Kheerganga/aayushmaan-sharma-oyvov12ISyA-unsplash_huh9hl.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131636/FOD%20Holidays/Kasol%20-%20Kheerganga/ashwini-chaudhary-monty-75mmGvxnTzA-unsplash_xwly0n.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131636/FOD%20Holidays/Kasol%20-%20Kheerganga/amlan-saha-kundu-t6mBids3T4k-unsplash_e8ac0r.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 5999 },
      { type: "triple", label: "Triple Sharing", price: 6499 },
      { type: "double", label: "Double Sharing", price: 6999 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Parvati Valley",
      "Manikaran",
      "Kasol Market",
      "Mini Thailand",
      "Hot Spring",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in parvati valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 7,
    name: "Kedarnath - Badrinath",
    desc: "A divine journey to the sacred shrines of Kedarnath and Badrinath. Experience spiritual serenity, Himalayan landscapes, and guided travel with comfortable stays and soulful evenings by the fire.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131722/FOD%20Holidays/Kedarnath%20-%20Badrinath/akshay-syal-5vDTocCCutE-unsplash_okfrqj.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131730/FOD%20Holidays/Kedarnath%20-%20Badrinath/gagan-deep-dXqbPIiJvYc-unsplash_jpeuqr.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131729/FOD%20Holidays/Kedarnath%20-%20Badrinath/shikhar-sharma-Pf-rTGteWyc-unsplash_u3wpea.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131725/FOD%20Holidays/Kedarnath%20-%20Badrinath/sajal-das-FcJS79vltI0-unsplash_wb0wmk.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131724/FOD%20Holidays/Kedarnath%20-%20Badrinath/krushna-patle-ZC7w_a6vS9c-unsplash_yxqiwz.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131724/FOD%20Holidays/Kedarnath%20-%20Badrinath/prateek-jaiswal-WigH_YWD2Z8-unsplash_mkvx6w.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131723/FOD%20Holidays/Kedarnath%20-%20Badrinath/avi-theret-2u6eLolV1JY-unsplash_bxz0pl.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131723/FOD%20Holidays/Kedarnath%20-%20Badrinath/muskan-verma-xk1NV4uTwg0-unsplash_dswtid.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131722/FOD%20Holidays/Kedarnath%20-%20Badrinath/abhay-paditkar-atrWLkNne0U-unsplash_vscrdi.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 14999 },
      { type: "triple", label: "Triple Sharing", price: 15899 },
      { type: "double", label: "Double Sharing", price: 16899 },
    ],
    duration: {
      day: 5,
      night: 4,
    },
    places_covered: [
      "Kedarnath",
      "Badrinath",
      "Devprayag",
      "Rishikesh",
      "Haridwar",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "4 Breakfast & 4 Dinner",
      "Bonfire under the sky in parvati valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 8,
    name: "Shimla - Manali Honeymoon",
    desc: "A dreamy honeymoon through the hills of Shimla and Manali. Enjoy snow-clad adventures, scenic sightseeing, romantic evenings, and cozy stays designed for couples seeking love, relaxation, and lasting memories.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132302/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/315_bsabok.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132348/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/yash-kiran-qxp9X5t9hQ4-unsplash_u4d5wq.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132348/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/vishal-bhutani-ugyfweYokVA-unsplash_igzbo0.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132344/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/tushar-sharma-3z7rmCH0gUg-unsplash_zk1mhq.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132340/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/romeio-paul-ys8aaPlRb24-unsplash_c6wph9.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132340/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/naman-pandey-y3nWJ-QznP4-unsplash_ykyngd.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132338/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/raghav-goyal-5cyaLryB3ek-unsplash_gmnlm3.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132338/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/naman-jaswani-Xpwj1j1HX34-unsplash_kyqwli.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132336/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/kumar-chandugade-65s0tySbm0I-unsplash_zu2npa.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132318/FOD%20Holidays/Shimla%20-%20Manali%20Honeymoon/aditya-chache-F4ybv3lThTs-unsplash_ld8pov.jpg",
    ],
    prices: [
      {
        type: "couple",
        label: "Couple Sharing",
        price: 34999,
        isHoneyMoon: true,
      },
    ],
    duration: {
      day: 7,
      night: 6,
    },
    places_covered: [
      "Shimla - Kufri",
      "Manali - Atal",
      "Kasol - Manikaran",
      "Mall Road",
      "Local Sightseeing",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "5 Breakfast & 5 Dinner",
      "Bonfire under the sky in tirthan valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 9,
    name: "Rishikesh Adventure",
    desc: "Dive into thrill and tranquility in Rishikesh. Experience river rafting, secret waterfalls, Ganga Aarti, and peaceful stays with bonfires and DJ nights on this short yet unforgettable Himalayan escape.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132241/FOD%20Holidays/Rishikesh%20Adventure/visual-voir-qDvc3Q2G7lo-unsplash_la2h5e.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132030/FOD%20Holidays/Rishikesh%20Adventure/narinder-pal-b9xWxpbe9vw-unsplash_antnkp.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132225/FOD%20Holidays/Rishikesh%20Adventure/prashant-bamnawat-kDwrlJlOmfw-unsplash_thumqx.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132020/FOD%20Holidays/Rishikesh%20Adventure/palak-pitroda-05DurkzaUsg-unsplash_anwams.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132231/FOD%20Holidays/Rishikesh%20Adventure/travel-with-enfield-mxoH7NtRJA8-unsplash_c1jjkf.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761132017/FOD%20Holidays/Rishikesh%20Adventure/akash-choudhary-CTdDooABASA-unsplash_d3lisq.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 5499 },
      { type: "triple", label: "Triple Sharing", price: 5999 },
      { type: "double", label: "Double Sharing", price: 6499 },
    ],
    duration: {
      day: 3,
      night: 2,
    },
    places_covered: [
      "Haridwar",
      "Ganga Aarti",
      "Secret Waterfall",
      "Ram Jhula",
      "Rafting",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "2 Breakfast & 2 Dinner",
      "Bonfire under the sky in tirthan valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 10,
    name: "Kedarnath Yatra",
    desc: "Set out on a spiritual journey to Kedarnath. Visit Guptkashi, Sonprayag, and Gaurikund, trek through divine routes, and find peace in the Himalayas with comfortable stays and guided support.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131729/FOD%20Holidays/Kedarnath%20-%20Badrinath/shikhar-sharma-Pf-rTGteWyc-unsplash_u3wpea.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131730/FOD%20Holidays/Kedarnath%20-%20Badrinath/gagan-deep-dXqbPIiJvYc-unsplash_jpeuqr.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131722/FOD%20Holidays/Kedarnath%20-%20Badrinath/akshay-syal-5vDTocCCutE-unsplash_okfrqj.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131725/FOD%20Holidays/Kedarnath%20-%20Badrinath/sajal-das-FcJS79vltI0-unsplash_wb0wmk.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131724/FOD%20Holidays/Kedarnath%20-%20Badrinath/krushna-patle-ZC7w_a6vS9c-unsplash_yxqiwz.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131724/FOD%20Holidays/Kedarnath%20-%20Badrinath/prateek-jaiswal-WigH_YWD2Z8-unsplash_mkvx6w.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131723/FOD%20Holidays/Kedarnath%20-%20Badrinath/avi-theret-2u6eLolV1JY-unsplash_bxz0pl.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131723/FOD%20Holidays/Kedarnath%20-%20Badrinath/muskan-verma-xk1NV4uTwg0-unsplash_dswtid.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131722/FOD%20Holidays/Kedarnath%20-%20Badrinath/abhay-paditkar-atrWLkNne0U-unsplash_vscrdi.jpg",
    ],
    prices: [
      { type: "quad", label: "Quad Sharing", price: 10999 },
      { type: "triple", label: "Triple Sharing", price: 11499 },
      { type: "double", label: "Double Sharing", price: 12999 },
    ],
    duration: {
      day: 6,
      night: 5,
    },
    places_covered: [
      "Guptkashi",
      "Rudraprayag",
      "Kedarnath",
      "Sonprayag",
      "Gaurikund",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "3 Breakfast & 3 Dinner",
      "Bonfire under the sky in tirthan valley",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 11,
    name: "Goa Honymoon Package",
    desc: "Celebrate love in Goa with beaches, candlelight dinners, and coastal adventures. Indulge in romantic evenings, cruises, and scenic beauty while staying at premium resorts designed for an unforgettable honeymoon experience.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131545/FOD%20Holidays/Goa%20Honymoon%20Package/Beach-Honeymoon-in-Goa_h6m0mj.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131545/FOD%20Holidays/Goa%20Honymoon%20Package/1296x864_z8biwt.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131562/FOD%20Holidays/Goa%20Honymoon%20Package/sumit-sourav-eSRtxPd9q1c-unsplash_t45qxa.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131558/FOD%20Holidays/Goa%20Honymoon%20Package/sarang-pande-IijeyJbmrec-unsplash_wddwoj.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131558/FOD%20Holidays/Goa%20Honymoon%20Package/smaran-alva-6l6GY7sLzRQ-unsplash_jjw4ow.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131557/FOD%20Holidays/Goa%20Honymoon%20Package/claudia-altamimi-EICXhtGFDAs-unsplash_thcryg.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131547/FOD%20Holidays/Goa%20Honymoon%20Package/alexey-turenkov-bWJiSZjIgTM-unsplash_i2hc7e.jpg",
    ],
    prices: [
      {
        type: "couple",
        label: "Couple Sharing",
        price: 22999,
        isHoneyMoon: true,
      },
    ],
    duration: {
      day: 6,
      night: 5,
    },
    places_covered: [
      "Sightseeing",
      "Cruise Ride",
      "Volvo",
      "Candlelight Dinner",
      "Meals",
    ],
    inclusions: [
      "Transit by Luxury Tempo Traveller/ Volvo bus",
      "Stay in 3 star property/Swiss Camps",
      "5 Breakfast & 5 Dinner",
      "Bonfire under the sky at beach",
      "Special DJ night around bonfire",
      "Professional Guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl:
      DEFAULT_WTSP_URL,
  },
  {
    id: 12,
    name: "Manali - Kasol Honeymoon",
    desc: "A romantic getaway through the valleys of Manali and Kasol. Enjoy scenic views, private sightseeing, floral decor, and cozy stays — perfect for couples seeking peace, adventure, and togetherness in nature.",
    images: [
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131474/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/Banner_Image_1_o8ltfv.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131345/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/nayan-tara-sOreumdCaKI-unsplash_pdmpad.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131344/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/lucas-hemingway-dpHgkc533z4-unsplash_bnlwgx.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131343/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/surya-teja-oIXJ839p55k-unsplash_woldbx.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131343/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/vishy-9ttisCSNCOc-unsplash_t6tzoy.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131342/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/vishal-bhutani-ugyfweYokVA-unsplash_onnb3s.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131340/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/ashwini-chaudhary-monty-EEsqZyA8b0E-unsplash_pdx5wv.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131339/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/naman-jaswani-Xpwj1j1HX34-unsplash_b8ong1.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131339/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/ishank-choudhary-8m4rHcyhePg-unsplash_onryfl.jpg",
      "https://res.cloudinary.com/dgghqzaxo/image/upload/v1761131338/FOD%20Holidays/Manali%20-%20Kasol%20Honeymoon/aditya-chache-F4ybv3lThTs-unsplash_ztml63.jpg",
    ],
    prices: [
      {
        type: "couple",
        label: "Couple Sharing",
        price: 16999,
        isHoneyMoon: true,
      },
    ],
    duration: {
      day: 6,
      night: 5,
    },
    places_covered: [
      "Kullu",
      "Manali",
      "Solang Valley",
      "Kasol",
      "Parvati Valley",
      "Manikaran",
    ],
    inclusions: [
      "Transit by Volvo bus",
      "Stay in 3 star property",
      "3 Breakfast & 3 Dinner",
      "Pickup and drop",
      "Flower decoratrion and cake",
      "Private cab for signt seeing",
      "Professional guide",
    ],
    exclusions: [
      "Anything that is not mentioned in inclusion",
      "Adventurous sports like rafting and paragliding",
      "Any personal expense",
    ],
    bookingUrl: DEFAULT_WTSP_URL,
  },
];

export const FAQ_DATA = {
  generalQuestions: [
    {
      ques: "How do I book a trip with your company?",
      ans: "You can book directly through our website by selecting your preferred package and dates. Alternatively, you can contact our travel experts through WhatsApp or call for personalized booking assistance.",
    },
    {
      ques: "What’s included in your travel packages?",
      ans: "Our packages generally include accommodation, transportation, sightseeing, and activities as listed in the itinerary. Meals, bonfires, and event nights may vary depending on the destination.",
    },
    {
      ques: "Are your trips suitable for solo travelers?",
      ans: "Absolutely! Many of our guests are solo travelers. We ensure a friendly, safe, and inclusive environment so you can make new friends while exploring new places.",
    },
    {
      ques: "Can I customize a tour package?",
      ans: "Yes, we offer fully customizable options. Whether you want to extend your stay, add destinations, or upgrade accommodations, our team can tailor your itinerary to fit your travel style.",
    },
    {
      ques: "What kind of accommodation do you provide?",
      ans: "We partner with verified hotels, camps, and homestays offering clean, comfortable, and safe stays. The type of accommodation depends on your package category — standard, deluxe, or premium.",
    },
    {
      ques: "What if I need to cancel or reschedule my trip?",
      ans: "We understand plans can change. Our cancellation and rescheduling policies are flexible — just reach out to our support team to know the applicable charges based on your package.",
    },
  ],
  frequentlyAskedQuestions: [
    {
      ques: "Do you organize group trips or private tours?",
      ans: "Yes! We offer both. You can join our fixed group departures for a fun, social experience, or book a private trip for a more personalized journey.",
    },
    {
      ques: "Are your tours safe for women travelers?",
      ans: "Safety is our top priority. We ensure verified stays, professional drivers, and 24/7 trip support. Many of our trips include women-only groups for added comfort and confidence.",
    },
    {
      ques: "How big are your travel groups?",
      ans: "Our groups usually range from 10–20 travelers, depending on the destination. We keep groups small to ensure personalized attention and a better travel experience.",
    },
    {
      ques: "What should I pack for a Himalayan trip?",
      ans: "Carry layered warm clothes, trekking shoes, personal medicines, a torch, and essentials like a power bank and reusable bottle. We’ll also share a detailed packing list before departure.",
    },
    {
      ques: "Do you provide travel insurance?",
      ans: "Yes, travel insurance can be arranged upon request. It’s highly recommended, especially for high-altitude or adventure destinations.",
    },
    {
      ques: "How do I stay updated about trip details after booking?",
      ans: "Once you book, you’ll receive a confirmation email and WhatsApp updates with your itinerary, meeting points, and trip manager details before departure.",
    },
  ],
};
