import type { Metadata } from "next";
import { Geist, Roboto, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const roboto = Roboto_Condensed({
  weight: '400',
  subsets: ['latin'],
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "FOD Holidays",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${geistSans.variable} antialiased`}
      >
        <Header/>
        <div className="pt-16">
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
